### ISSUE TITLE
Exception Thrown WritablePipe.php(275)

### ISSUE THREAD

**Issue by karl-malakoff** [icicleio/stream#4]
I've seen this exception thrown a couple times from WritablePipe.php. Due to the inability to catch exceptions thrown here it causes a crash. I haven't been able to investigate it further since it happens rarely and only while I'm not looking.

Fatal error: Uncaught RuntimeException: Can't shift from an empty datastructure in .\vendor\icicleio\stream\src\Pipe\WritablePipe.php:275
Stack trace:
#0 .\vendor\icicleio\stream\src\Pipe\WritablePipe.php(275): SplDoublyLinkedList->shift()
#1 .\vendor\icicleio\icicle\src\Loop\Watcher\Io.php(68): Icicle\Stream\Pipe\WritablePipe::Icicle\Stream\Pipe{closure}(Resource id #88334, true, Object(Icicle\Loop\Watcher\Io))
#2 .\vendor\icicleio\icicle\src\Loop\Manager\Select\SelectIoManager.php(67): Icicle\Loop\Watcher\Io->call(true)
#3 .\vendor\icicleio\icicle\src\Loop\Watcher\Timer.php(93): Icicle\Loop\Manager\Select\SelectIoManager->Icicle\Loop\Manager\Select{closure}(Object(Icicle\Loop\Watcher\Timer))
#4 .\vendor\icicleio\icicle\src\Loop\Manager\Select\SelectTimerManager.php(185): Icicle\Loop\Watcher\Timer->call()
#5 .\vendor\icicleio\icicle\src\Loop\SelectLoop.php(83): Icicle\Loop\Manager\Select\SelectTimerManager->tick()
#6 . in .\vendor\icicleio\stream\src\Pipe\WritablePipe.php on line 275

**Comment by jvasseur** [comment]
I'm having the same error.

I tried to debug it a bit and found that when the error happens, `$expired` is set to `true`. I think this is a timeout that is still happening after everything in the writeQueue has been written.

**Comment by trowski** [comment]
@karl-malakoff and @jvasseur Which loop implementation are you using? Just `SelectLoop`?

**Comment by jvasseur** [comment]
Yes, the `SelectLoop`

**Comment by trowski** [comment]
I just tagged [v0.9.6](https://github.com/icicleio/icicle/releases/tag/v0.9.6) of Icicle, can you update to this version (or if you're using master pull the latest commit) and see if you still get the same behavior. https://github.com/icicleio/icicle/commit/1d5a4de89c2d820ce8642970c82cdfa487ef6edd may fix this issue.

**Comment by jvasseur** [comment]
I don't have those errors anymore after updating Icicle, thanks for the fix.

**Comment by trowski** [comment]
@karl-malakoff How about for you? Please update Icicle and let me know if you're still occasionally seeing exceptions.

**Comment by karl-malakoff** [comment]
I haven't seen it again but I only saw it very rarely before. If it happens again I'll let you know.
